(el-get-bundle tarao/el-get-lock)
(el-get-lock)

(el-get-bundle ag)
(el-get-bundle anzu)
(el-get-bundle auto-highlight-symbol)
(el-get-bundle c-eldoc)
(el-get-bundle company-c-headers)
(el-get-bundle company-irony)
(el-get-bundle cmake-mode)
(el-get-bundle diminish)
(el-get-bundle emacs-jp/replace-colorthemes)
(el-get-bundle elpa:ess)
(el-get-bundle elpa:git-commit)
(el-get-bundle git-gutter+)
(el-get-bundle git-gutter-fringe+)
(el-get-bundle google-this)
(el-get-bundle helm)
(el-get-bundle helm-ag)
(el-get-bundle helm-ag-r)
(el-get-bundle helm-company)
(el-get-bundle helm-git-files)
(el-get-bundle helm-git-grep)
(el-get-bundle helm-gtags)
(el-get-bundle helm-ls-git)
(el-get-bundle helm-swoop)
(el-get-bundle hiwin)
(el-get-bundle irony-eldoc)
(el-get-bundle magit)
(el-get-bundle markdown-mode)
(el-get-bundle ruediger/matlab-emacs :name matlab-mode) ; default recipe uses cvs, which does not work behind proxy
(el-get-bundle polymode)
(el-get-bundle rtags)
(el-get-bundle smartparens)
(el-get-bundle smex)
(el-get-bundle volatile-highlights)
(el-get-bundle mhayashi1120/Emacs-wgrep :name wgrep)
(el-get-bundle wgrep-ag)
(el-get-bundle yaml-mode)
